export const FETCH_CAROUSEL='FETCH_CAROUSEL';
export const FETCH_AS_USED_BY='FETCH_AS_USED_BY';
export const FETCH_WORK_DONE='FETCH_WORK_DONE';
export const FETCH_FEATURES='FETCH_FEATURES';
export const FETCH_CROWD_FAV ='FETCH_CROWD_FAV ';
export const FETCH_CATEGORIES='FETCH_CATEGORIES';
export const FETCH_CARDS='FETCH_CARDS';
export const FETCH_TOP_JOB='FETCH_TOP_JOB';
